### ISSUE TITLE
latest package on pypi requires impossible napari

### ISSUE THREAD

**Issue by tlambert03** [AbigailMcGovern/paintedlife#1]
Not sure how this happened... since the `setup.py` here looks fine, but if you try to pip install, you get:
```
ERROR: No matching distribution found for napari[all]>=4.0.0
```

indeed... in the latest wheel at https://pypi.org/project/paintedlife/#files, in the `.dist-info/METADATA` file it says:
```
Requires-Dist: napari[all] (>=4.0.0)
```

the people need easy access to paintedlife! :joy:

**Comment by AbigailMcGovern** [comment]
Thanks for this @tlambert03! It should work now.

Dyslexia strikes again 🤦‍♀️🤦‍♀️🤦‍♀️ 😂
